name: aria2

on:
  workflow_dispatch:
  push:
    paths:
    - 'aria2/PKGBUILD'

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: base-devel gcc autotools zlib-devel libgnutls-devel gettext-devel
    - uses: actions/checkout@v4
    - name: Build
      shell: msys2 {0}
      run: |
        cd /d/a/nginx-nosni/nginx-nosni/aria2; makepkg
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: aria2*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: aria2/*.zst
        tag: latest
        overwrite: true
        file_glob: true
