name: msys2-runtime

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: base-devel gcc git fish
    - uses: actions/checkout@v4
    - name: Build
      shell: msys2 {0}
      run: |
        cd /d/a/nginx-nosni/nginx-nosni; fish build_msys2.fish
    # - uses: mxschmitt/action-tmate@v3
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: MSYS2-packages-master/msys2-runtime/*.zst
        tag: latest
        overwrite: true
        file_glob: true
