name: msys2

on:
  workflow_dispatch:
  push:
    paths:
    - 'PKGBUILD'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Build
      run: |
        python init.py
        C:\msys64\usr\bin\bash -lc 'cd /d/a/nginx-nosni/nginx-nosni; source init.sh; pacman -Sy gcc zlib-devel openssl-devel --noconfirm; MSYSTEM=msys2 makepkg'
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: nginx*pkg*
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: nginx*pkg*
        tag: latest
        overwrite: true
        file_glob: true
