name: msys2-runtime

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Build
      run: |
        C:\msys64\usr\bin\bash -lc 'pacman -Sy base-devel gcc git fish --noconfirm'
        C:\msys64\usr\bin\bash -lc 'cd /c/a/nginx-nosni/nginx-nosni; fish build_msys2.fish'
    # - uses: mxschmitt/action-tmate@v3
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: MSYS2-packages-master/msys2-runtime/*.zst
        tag: latest
        overwrite: true
        file_glob: true
