name: nginx

on:
  workflow_dispatch:
  push:
    paths:
    - 'PKGBUILD'

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: base-devel gcc zlib-devel openssl-devel
    - uses: actions/checkout@v2
    - name: Build
      shell: msys2 {0}
      run: |
        cd /d/a/nginx-nosni/nginx-nosni; /c/hostedtoolcache/windows/python/3.7.9/x64/python init.py; source init.sh; makepkg
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: nginx*pkg*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: nginx*pkg*
        tag: latest
        overwrite: true
        file_glob: true
