name: nginx

on:
  workflow_dispatch:
  push:
    paths:
    - 'PKGBUILD'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Build
      run: |
        C:\msys64\usr\bin\bash -lc 'pacman -Sy base-devel gcc zlib-devel openssl-devel --noconfirm'
        C:\msys64\usr\bin\bash -lc 'cd /c/a/nginx-nosni/nginx-nosni; /c/hostedtoolcache/windows/python/3.9.13/x64/python init.py; source init.sh; makepkg'
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: nginx*pkg*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: nginx*pkg*
        tag: latest
        overwrite: true
        file_glob: true
