name: whisper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        git clone https://github.com/openai/whisper
        git clone https://github.com/ggerganov/whisper.cpp
        cd whisper.cpp/models
        pip install -U "huggingface_hub[cli]" torch numpy
        huggingface-cli download efwkjn/whisper-ja-anime-v0.3 --local-dir ./anime-whisper
        python ./convert-h5-to-ggml.py ./anime-whisper/ ../../whisper .
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: whisper.cpp/models/ggml-model.bin
        tag: latest
        overwrite: true
        file_glob: true
