name: whisper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        git clone https://github.com/openai/whisper
        pip install -U "huggingface_hub[cli]" torch numpy transformers safetensors
        huggingface-cli download efwkjn/whisper-ja-anime-v0.3 --local-dir ./anime-whisper
        python ./turbo2ggml.py ./anime-whisper/ whisper .
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ggml-model.bin
        tag: latest
        overwrite: true
        file_glob: true
